#!/usr/bin/env python3
"""
Install a per-user LaunchAgent on macOS that runs `signal-cli receive` on a schedule.

Keeps signal-cli accounts active by fetching messages periodically while the user
is logged in. Uses launchd (not cron) so jobs align with macOS login sessions.
"""

from __future__ import annotations

import os
import plistlib
import subprocess
import sys
from pathlib import Path
from typing import Tuple


def _job_id(phone_number: str) -> str:
    return "".join(c for c in phone_number if c.isdigit())


def support_dir() -> Path:
    return Path.home() / "Library/Application Support/signal-voip-registration-helper"


def logs_dir() -> Path:
    p = Path.home() / "Library/Logs/signal-voip-registration-helper"
    return p


def script_path(phone_number: str) -> Path:
    return support_dir() / f"receive-{_job_id(phone_number)}.sh"


def plist_filename(phone_number: str) -> str:
    return f"org.signal.voip-helper.receive.{_job_id(phone_number)}.plist"


def plist_path(phone_number: str) -> Path:
    return Path.home() / "Library/LaunchAgents" / plist_filename(phone_number)


def _launchctl_bootout(plist: Path) -> None:
    uid = str(os.getuid())
    subprocess.run(
        ["launchctl", "bootout", f"gui/{uid}", str(plist)],
        capture_output=True,
        text=True,
    )
    subprocess.run(
        ["launchctl", "unload", str(plist)],
        capture_output=True,
        text=True,
    )


def _launchctl_bootstrap(plist: Path) -> Tuple[bool, str]:
    uid = str(os.getuid())
    r = subprocess.run(
        ["launchctl", "bootstrap", f"gui/{uid}", str(plist)],
        capture_output=True,
        text=True,
    )
    if r.returncode == 0:
        return True, ""
    r2 = subprocess.run(
        ["launchctl", "load", "-w", str(plist)],
        capture_output=True,
        text=True,
    )
    if r2.returncode == 0:
        return True, ""
    err = (r.stderr or r.stdout or "") + "\n" + (r2.stderr or r2.stdout or "")
    return False, err.strip() or "launchctl failed"


def _write_receive_script(phone_number: str) -> None:
    support_dir().mkdir(parents=True, exist_ok=True)
    path = script_path(phone_number)
    body = f"""#!/bin/bash
# Auto-generated by signal-voip-registration-helper — fetch Signal messages for this account.
# Do not edit by hand; re-run the helper to change the schedule.

set -euo pipefail
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"
PHONE="{phone_number}"

if ! command -v signal-cli >/dev/null 2>&1; then
  echo "$(date) signal-cli not found in PATH" >&2
  exit 1
fi

exec signal-cli -a "$PHONE" receive
"""
    path.write_text(body, encoding="utf-8")
    os.chmod(path, 0o755)
    if not path.is_file():
        raise OSError(f"Failed to write receive script: {path}")


def _write_plist(phone_number: str) -> None:
    logs_dir().mkdir(parents=True, exist_ok=True)
    jid = _job_id(phone_number)
    label = f"org.signal.voip-helper.receive.{jid}"
    sh = script_path(phone_number)
    out_log = logs_dir() / f"receive-{jid}.log"
    err_log = logs_dir() / f"receive-{jid}.err.log"

    data = {
        "Label": label,
        "ProgramArguments": ["/bin/bash", str(sh)],
        "RunAtLoad": True,
        "StartCalendarInterval": [
            {"Hour": 9, "Minute": 0},
            {"Hour": 21, "Minute": 0},
        ],
        "StandardOutPath": str(out_log),
        "StandardErrorPath": str(err_log),
        "ThrottleInterval": 300,
        "ProcessType": "Background",
    }

    launch_agents = Path.home() / "Library/LaunchAgents"
    launch_agents.mkdir(parents=True, exist_ok=True)
    plist_file = plist_path(phone_number)
    with open(plist_file, "wb") as f:
        plistlib.dump(data, f)
    os.chmod(plist_file, 0o644)


def install_receive_job(phone_number: str) -> Tuple[bool, str]:
    """
    Install LaunchAgent + script. Safe to call again (overwrites and reloads).
    Recreates a missing .sh file if the plist is still present.
    """
    if not phone_number.startswith("+"):
        return False, "Phone number must include country code (e.g. +15551234567)"

    try:
        _write_receive_script(phone_number)
    except OSError as e:
        return False, str(e)

    pl = plist_path(phone_number)
    if pl.exists():
        _launchctl_bootout(pl)

    _write_plist(phone_number)

    ok, err = _launchctl_bootstrap(pl)
    if not ok:
        return (
            False,
            f"Could not load the LaunchAgent automatically.\n{err}\n\n"
            "Try: launchctl bootstrap gui/$(id -u) "
            f"'{pl}'\nOr log out and back in — LaunchAgents in ~/Library/LaunchAgents "
            "often load at login.",
        )
    return True, str(plist_path(phone_number))


def needs_receive_job_repair(phone_number: str) -> bool:
    """Plist is present but the shell script is missing (broken install)."""
    return plist_path(phone_number).is_file() and not script_path(phone_number).is_file()


def uninstall_receive_job(phone_number: str) -> Tuple[bool, str]:
    pl = plist_path(phone_number)
    if pl.exists():
        _launchctl_bootout(pl)
        try:
            pl.unlink()
        except OSError as e:
            return False, str(e)

    sp = script_path(phone_number)
    if sp.exists():
        try:
            sp.unlink()
        except OSError as e:
            return False, str(e)

    return True, "Removed scheduled job and LaunchAgent plist (if present)."


def is_receive_job_installed(phone_number: str) -> bool:
    """True only when both LaunchAgent plist and receive script exist."""
    return plist_path(phone_number).is_file() and script_path(phone_number).is_file()


def main() -> None:
    if len(sys.argv) < 3:
        print(
            "Usage:\n"
            "  python3 signal_receive_job.py install +15551234567\n"
            "  python3 signal_receive_job.py uninstall +15551234567",
            file=sys.stderr,
        )
        sys.exit(2)
    cmd, phone = sys.argv[1], sys.argv[2]
    if cmd == "install":
        ok, msg = install_receive_job(phone)
    elif cmd == "uninstall":
        ok, msg = uninstall_receive_job(phone)
    else:
        print(f"Unknown command: {cmd}", file=sys.stderr)
        sys.exit(2)
    if ok:
        print(msg)
        sys.exit(0)
    print(msg, file=sys.stderr)
    sys.exit(1)


if __name__ == "__main__":
    main()
